sudo: required

language: python
python:
  - '3.6'

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script: pytest --capture=no --log-cli-level=INFO
    - stage: deploy
      script: python setup.py sdist bdist_wheel
      deploy:
        provider: pypi
        username: '__token__'
        password: $PYPI_TOKEN
        on:
          branch: master

stages:
  - test
  - deploy
